name: mobile_report
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  velocity_x: 4.2.1
  google_fonts: 6.2.1
  getwidget: 4.0.0
  get_storage: 2.1.1
  image_picker: 1.1.2
  dio: 5.7.0
  flutter: 
    sdk: flutter
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.3
  objectbox_flutter_libs:
  objectbox: ^4.0.3
  path_provider: ^2.1.5
  intl: ^0.19.0


dev_dependencies: 
  flutter_lints: ^3.0.0
  build_runner: ^2.1.4
  objectbox_generator: any
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/images/
  uses-material-design: true

